name: 'Dev-Branch-CI'

on:
  push:
    branches: [ "ROBO-*" ]

permissions:
  contents: read

jobs:
  DevBranchCI:
    name: 'DevBranchCI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NodeJS Dependencies
      run: git branch -a

#