name: 'Main-Branch-CI'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  MainBranchCI:
    name: 'MainBranchCI'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NodeJS Dependencies
      run: npm install

    - name: Docker build
      run: docker build -t 633788536644.dkr.ecr.us-east-1.amazonaws.com/cart:${GITHUB_RUN_NUMBER} .

    - name: Docker Login
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 633788536644.dkr.ecr.us-east-1.amazonaws.com

    - name: Docker Push
      run: docker push 633788536644.dkr.ecr.us-east-1.amazonaws.com/cart:${GITHUB_RUN_NUMBER}

    - name: Create local changes
      run: |
        echo ${GITHUB_RUN_NUMBER} >> helm/dev.yaml
        echo ${GITHUB_RUN_NUMBER} >> helm/prod.yaml

    - name: Commit & Helm Version changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}

    - name: Merge main -> deploy
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: main
        target_branch: deploy
        github_token: ${{ secrets.TOKEN_GITHUB }}
