name: 'Main-Branch-CI'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  MainBranchCI:
    name: 'MainBranchCI'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NodeJS Dependencies
      run: npm install

    - name: Docker build
      run: docker build -t 633788536644.dkr.ecr.us-east-1.amazonaws.com/cart:latest .


