name: 'ReleaseWithTag'

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  PR:
    name: 'ReleaseWithTag'
    runs-on:
      labels: self-hosted
#    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install NodeJS Dependencies
      run: env

    - name: Create Archive
      run: |
        echo $GITHUB_REF_NAME > VERSION
        echo zip -r cart-$GITHUB_REF_NAME.zip *

#
#    - name: Run Test Cases
#      run: echo npm test
#
#    - name: Run Integration Cases
#      run: echo npm test


